server:
  port: 8090

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # --- MICROSERVICIOS PROTEGIDOS CON JWT ---
        - id: ms-productos
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**
          filters:
            - AuthenticationFilter # <-- Valida el JWT antes de dejar pasar

        - id: ms-categorias
          uri: http://localhost:8083
          predicates:
            - Path=/api/categorias/**
          filters:
            - AuthenticationFilter

        - id: ms-stock
          uri: http://localhost:8085
          predicates:
            - Path=/api/stock/**
          filters:
            - AuthenticationFilter

        - id: ms-ventas
          uri: http://localhost:8081
          predicates:
            - Path=/api/ventas/**
          filters:
            - AuthenticationFilter

        - id: ms-sucursales
          uri: http://localhost:8084
          predicates:
            - Path=/api/sucursales/**
          filters:
            - AuthenticationFilter

        - id: ms-kpi
          uri: http://localhost:8087
          predicates:
            - Path=/api/kpi/**
          filters:
            - AuthenticationFilter

        - id: ms-autenticacion
          uri: http://localhost:8088
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

        - id: ms-integracion-datos
          uri: http://localhost:8000
          predicates:
            - Path=/api/integracion/**
