server:
  port: 8090  # Puerto de entrada para todo el sistema

spring:
  cloud:
    gateway:
      routes:
        # Ruta para el microservicio de Gestion de Datos
        - id: gestion-datos-route
          uri: http://localhost:8082  # Direccion donde corre tu microservicio actual
          predicates:
            - Path=/api/** # Todo lo que empiece por /api se redirige